### PR TITLE
Remove duplicate keybind

### PR DESCRIPTION
**Pull request by Alexdoru**
There are two identical keybinds regitered and they do the same thing, so I removed one of them

remove one of two keybinds that does the same thing : "Switch between Day/Night/Caves"

### CODE REVIEW

**Comment by Alexdoru** [comment]
what is this thing, I ain't clicking any link that's asking for access to my github account

**Comment by mysticdrew** [comment]
> what is this thing, I ain't clicking any link that's asking for access to my github account

It is the cla, contributor license agreement. It must be signed before I can merge your pr.

**Review by mysticdrew — APPROVED** [review]
Thanks for the PR, not sure why it was done that way. Will merge once the cla is signed.

**Comment by Alexdoru** [comment]
I signed

**Comment by mysticdrew** [comment]
thank you

**Pull request merged**
